//
// Created by Qiwei Li on 6/26/22.
//

import Foundation

public let ENVIRONMENT_DB_KEY = "DATABASE_URL"
public let ENVIRONMENT_ACCESS_KEY = "ACCESS_KEY"
public let ENVIRONMENT_SECRET_KEY = "SECRET_KEY"
public let ENVIRONMENT_S3_ENDPOINT = "ENDPOINT"
public let ENVIRONMENT_S3_REGION = "REGION"
public let ENVIRONMENT_S3_BUCKET_NAME = "BUCKET_NAME"
public let ENVIRONMENT_TRANSCODING_URL = "TRANSCODING_URL"
/**
 JWT Password
 */
public let ENVIRONMENT_PASSWORD = "PASSWORD"
