name: Release docker image

on:
  release:
    types:
      - released

jobs:
  serverless-functions:
    name: Deploy cloudflare serverless functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: ["authentication"]
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "functions/${{ matrix.function }}"
          command: "deploy"

  docker-service:
    name: Build dockerized services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:  ["video/video_upload_service", "video/video_transcode_service"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{ matrix.app }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./docker/services/service.dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.app }}:${{ github.event.release.tag_name }}
          build-args: |
            APP_NAME=${{ matrix.app }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
