name: Test and Build project

on:
  push:

jobs:
  test-services:
    name: "Test Swift Packages"
    runs-on: self-hosted
    strategy:
      matrix:
        app:  ["video/video_upload_service"]
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
      - name: Up required services
        run: docker-compose up -d
      - name: Test ${{ matrix.app }}
        run: swift test
        working-directory: services/${{ matrix.app }}
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ (github.event.pusher.name != 'github action') && (github.ref == 'refs/heads/main') }}
    needs: 
      - test-services
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          branch: main